/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/AppLayout.vue')['default']
    AsyncState: typeof import('./components/AsyncState.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    GeetestCaptcha: typeof import('./components/GeetestCaptcha.vue')['default']
    HostCard: typeof import('./components/HostCard.vue')['default']
    HostTable: typeof import('./components/HostTable.vue')['default']
    IpTimeline: typeof import('./components/IpTimeline.vue')['default']
    MetricChart: typeof import('./components/MetricChart.vue')['default']
    ProbeHistoryPanel: typeof import('./components/ProbeHistoryPanel.vue')['default']
    ProbeOverview: typeof import('./components/ProbeOverview.vue')['default']
    ProcessTopTable: typeof import('./components/ProcessTopTable.vue')['default']
    PublicLayout: typeof import('./components/PublicLayout.vue')['default']
    RecoveryCodesNotice: typeof import('./components/two-factor/RecoveryCodesNotice.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderCaptcha: typeof import('./components/SliderCaptcha.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    SummaryBar: typeof import('./components/SummaryBar.vue')['default']
    TimeRangePicker: typeof import('./components/TimeRangePicker.vue')['default']
    TwoFactorBindForm: typeof import('./components/two-factor/TwoFactorBindForm.vue')['default']
    TwoFactorPanel: typeof import('./components/two-factor/TwoFactorPanel.vue')['default']
    TwoFactorUnbindForm: typeof import('./components/two-factor/TwoFactorUnbindForm.vue')['default']
  }
}
